modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="cave_enhancements"
version="${file.jarVersion}"
displayURL="https://github.com/Team-Abode/Cave-Enhancements-Forge"
displayName="Cave Enhancements"
logoFile="icon.png"
credits="Thanks to our other contributors; Chikorita Lover, Firch, BardinTheDwarf, & junshengxie."
authors="Team Abode"
description='''
    Expands upon the underground by adding in new & exciting features!
'''

[[dependencies.cave_enhancements]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.cave_enhancements]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cave_enhancements]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[6.1.0,)"
    ordering = "BEFORE"
    side = "BOTH"
