@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.kekecreations.cave_enhancements.effect;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;